version: 2.1
jobs:
  NetLRTS:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Build
          command: ./build LIBS netlrts-linux-x86_64 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla
      - run:
          name: Test
          command: make -C netlrts-linux-x86_64/tmp -j3 all-test-tests all-test-examples OPTS="-g" &&  make -C netlrts-linux-x86_64/tmp test-tests test-examples TESTOPTS="++local"
 
  NetLRTS-smp:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - checkout
      - run:
          name: Build
          command: ./build LIBS netlrts-linux-x86_64 smp -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla
      - run:
          name: Test
          command: make -C netlrts-linux-x86_64-smp/tmp -j3 all-test-tests all-test-examples OPTS="-g" && make -C netlrts-linux-x86_64-smp/tmp test-tests test-examples TESTOPTS="++local +setcpuaffinity +CmiSleepOnIdle"
 
workflows:
  version: 2
  build:
    jobs:
      - NetLRTS
      - NetLRTS-smp
