name: NetLRTS Linux buildold

on: [push]

jobs:
  build:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./buildold LIBS netlrts-linux-x86_64 -g -j4 --with-production
    - name: test
      run: |
        make -C netlrts-linux-x86_64/tests all OPTS="-g" -j4
        make -C netlrts-linux-x86_64/tests test TESTOPTS="++local"
