name: Multicore Darwin tracing

on: [push]

jobs:
  build:
    timeout-minutes: 60

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build LIBS multicore-darwin-x86_64 -g -j3 --with-production --enable-tracing
    - name: test
      run: |
        make -C multicore-darwin-x86_64/tests all -j3 OPTS="-tracemode projections"
        make -C multicore-darwin-x86_64/tests test
        make -C multicore-darwin-x86_64/examples all -j3 OPTS="-tracemode projections"
        make -C multicore-darwin-x86_64/examples test
        make -C multicore-darwin-x86_64/benchmarks all -j3 OPTS="-tracemode projections"
        make -C multicore-darwin-x86_64/benchmarks test
    - name: projections
      run: |
        git clone https://github.com/UIUC-PPL/projections
        cd projections
        make
        proj=$PWD/bin/projections
        cd ..
        files=$(find . -name *.sts)
        for f in $files; do echo $f; pushd .; cd $(dirname $f); $proj --exit $(basename $f); popd; done
