name: Spack

on: pull_request

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]


    steps:
    - uses: actions/checkout@v2

    - name: Install Spack
      run: |
        cd ..
        git clone --depth 1 https://github.com/spack/spack
        cd spack
        [[ $(uname) == "Linux" ]] && sudo apt-get install -y gfortran gfortran-7 gfortran-8 gfortran-9 gfortran-10

        # Use this branch for testing, not master
        sed -i -e 's,="master",="${{ github.head_ref }}",' var/spack/repos/builtin/packages/charmpp/package.py

        # Compile with debug symbols
        sed -i -e 's,build(target,options.append("-g"); build(target,' var/spack/repos/builtin/packages/charmpp/package.py

        # Add +setcpuaffinity option to TESTOPTS
        sed -i -e 's,\+\+local,++local +setcpuaffinity,' var/spack/repos/builtin/packages/charmpp/package.py

        # No need for automake/autoconf
        sed -i -e '/automake/d' var/spack/repos/builtin/packages/charmpp/package.py
        sed -i -e '/autoconf/d' var/spack/repos/builtin/packages/charmpp/package.py

    - name: Build Charm++
      run: |
        cd ../spack
        source share/spack/setup-env.sh
        spack compiler find
        spack compiler list
        # See bug #3168:
        [[ $(uname) == "Linux" ]] && smp="~smp"
        spack install -v --test root charmpp@master $smp
