name: UCX 1.7.0 Linux

on: [push]

jobs:
  build:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Uncomment the lines below to set up a tmate session for debugging. 
    # See https://github.com/marketplace/actions/debugging-with-tmate for details.
    # This can't be enabled all the time as the tmate session will wait for a user to connect before running
    # the build.
    #- name: Tmate session for debugging
    #  uses: mxschmitt/action-tmate@v2
    - name: build-ucx
      run: git clone --branch v1.7.0 https://github.com/openucx/ucx.git && cd ucx && ./autogen.sh && ./contrib/configure-release --disable-numa && make -j4 && sudo make install
    - name: build-ompi
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.1.tar.gz && tar -xf openmpi-4.0.1.tar.gz && cd openmpi-4.0.1/ && ./configure --enable-mca-no-build=btl-uct --enable-install-libpmix && make -j 4 && sudo make install
    - name: build
      run: ./build all-test ucx-linux-x86_64 ompipmix -g -j4 --with-production
    - name: test
      run: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && export OMPI_MCA_rmaps_base_oversubscribe=1 && make -C ucx-linux-x86_64-ompipmix/tests test && make -C ucx-linux-x86_64-ompipmix/examples test
