name: UCX Linux

on: [pull_request, merge_group]

jobs:
  build:
    timeout-minutes: 60

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    # Uncomment the lines below to set up a tmate session for debugging.
    # See https://github.com/marketplace/actions/debugging-with-tmate for details.
    # This can't be enabled all the time as the tmate session will wait for a user to connect before running
    # the build.
    #- name: Tmate session for debugging
    #  uses: mxschmitt/action-tmate@v2
    - name: install-prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install libucx-dev libevent-dev libhwloc-dev
    - name: build-openpmix
      run: |
        wget https://github.com/openpmix/openpmix/releases/download/v3.1.5/pmix-3.1.5.tar.gz
        tar -xf pmix-3.1.5.tar.gz
        cd pmix-3.1.5
        ./configure
        make -j4
        sudo make install
    # OpenMPI is needed to launch Charm++ programs with the UCX backend
    - name: build-ompi
      run: |
        wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.gz
        tar -xf openmpi-4.0.5.tar.gz
        cd openmpi-4.0.5
        ./configure --enable-mca-no-build=btl-uct --with-pmix=/usr/local
        make -j4
        sudo make install
    - name: build
      run: ./build all-test ucx-linux-x86_64 openpmix -g -j4 --with-production
    - name: test
      run: |
        export PATH=/usr/local/bin:$PATH
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        export OMPI_MCA_rmaps_base_oversubscribe=1
        make -C ucx-linux-x86_64-openpmix/tests test
        make -C ucx-linux-x86_64-openpmix/examples test
