name: UTH Linux

on: [push]

jobs:
  build:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./build all-test uth-linux-x86_64 -g -j4 --with-production
    - name: test
      run: make -C uth-linux-x86_64/tmp test
    - name: testp P=2
      run: make -C uth-linux-x86_64/tmp testp P=2
