name: Verbs Linux SMP

# Buildonly test, as the machine layer needs an actual device to run.

on: [push]

jobs:
  build:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        sudo apt-get update
        sudo apt-get -y install libibverbs-dev
        ./build all-test verbs-linux-x86_64 smp -j4
